In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
mem = pd.read_csv("member.csv")
tran = pd.read_csv("transaction.csv")

In [3]:
mem

id  recency   zip_code  is_referral       channel  conversion
0      906145       10  Surburban            0         Phone           0
1      184478        6      Rural            1           Web           0
2      394235        7  Surburban            1           Web           0
3      130152        9      Rural            1           Web           0
4      940352        2      Urban            0           Web           0
...       ...      ...        ...          ...           ...         ...
63995  838295       10      Urban            0           Web           0
63996  547316        5      Urban            1         Phone           0
63997  131575        6      Urban            1         Phone           0
63998  603659        1  Surburban            1  Multichannel           0
63999  254229        1  Surburban            0           Web           0

[64000 rows x 6 columns]

In [4]:
tran

id  num_item  total_amount
0       906145         5         34000
1       906145         1         27000
2       906145         4         33000
3       184478         4         29000
4       394235         4         33000
...        ...       ...           ...
196831  536246         5         24000
196832  927617         5         26000
196833  927617         3         22000
196834  927617         3         18000
196835  927617         3         20000

[196836 rows x 3 columns]

In [5]:
data = tran.head(1000)

In [6]:
data.groupby('id').sum().reset_index()

id  num_item  total_amount
0    101354         8         81000
1    102658        13         98000
2    103128         4         69000
3    103308         9         53000
4    107253        11         67000
..      ...       ...           ...
336  980721        11         66000
337  982341         3         27000
338  982358         8         73000
339  990129         2         17000
340  993410        13         94000

[341 rows x 3 columns]

In [7]:
tran['avg_price'] = tran['total_amount'] / tran['num_item']

In [8]:
tran_mean = tran.groupby('id').mean()

In [9]:
tran_cnt = tran['id'].value_counts()

In [10]:
tran_mean

num_item  total_amount     avg_price
id                                          
100001  3.500000  26000.000000   7500.000000
100008  5.000000  26000.000000   5200.000000
100032  2.666667  20666.666667   9366.666667
100036  3.000000  25800.000000  13273.333333
100070  3.250000  21250.000000   8537.500000
...          ...           ...           ...
999932  5.000000  32000.000000   6400.000000
999981  2.000000  22750.000000  12875.000000
999990  3.000000  28000.000000  10388.888889
999995  2.000000  27000.000000  13500.000000
999997  2.000000  13000.000000   6500.000000

[64000 rows x 3 columns]

In [11]:
tran_cnt

446874    5
473857    5
384266    5
648461    5
130318    5
         ..
674652    1
670546    1
192229    1
720615    1
789077    1
Name: id, Length: 64000, dtype: int64

In [12]:
tran_df =pd.concat([tran_mean, tran_cnt],axis=1)

In [13]:
tran_df = tran_df.rename(columns={'id':'count'})

In [14]:
tran_df

num_item  total_amount     avg_price  count
100001  3.500000  26000.000000   7500.000000      2
100008  5.000000  26000.000000   5200.000000      1
100032  2.666667  20666.666667   9366.666667      3
100036  3.000000  25800.000000  13273.333333      5
100070  3.250000  21250.000000   8537.500000      4
...          ...           ...           ...    ...
999932  5.000000  32000.000000   6400.000000      1
999981  2.000000  22750.000000  12875.000000      4
999990  3.000000  28000.000000  10388.888889      3
999995  2.000000  27000.000000  13500.000000      1
999997  2.000000  13000.000000   6500.000000      1

[64000 rows x 4 columns]

In [15]:
mem.set_index('id', inplace=True)

In [16]:
mem

recency   zip_code  is_referral       channel  conversion
id                                                               
906145       10  Surburban            0         Phone           0
184478        6      Rural            1           Web           0
394235        7  Surburban            1           Web           0
130152        9      Rural            1           Web           0
940352        2      Urban            0           Web           0
...         ...        ...          ...           ...         ...
838295       10      Urban            0           Web           0
547316        5      Urban            1         Phone           0
131575        6      Urban            1         Phone           0
603659        1  Surburban            1  Multichannel           0
254229        1  Surburban            0           Web           0

[64000 rows x 5 columns]

In [17]:
data = mem.join(tran_df)

In [18]:
data.isna().sum()

recency         0
zip_code        0
is_referral     0
channel         0
conversion      0
num_item        0
total_amount    0
avg_price       0
count           0
dtype: int64

In [19]:
data

recency   zip_code  is_referral       channel  conversion  num_item  \
id                                                                            
906145       10  Surburban            0         Phone           0  3.333333   
184478        6      Rural            1           Web           0  4.000000   
394235        7  Surburban            1           Web           0  4.000000   
130152        9      Rural            1           Web           0  1.750000   
940352        2      Urban            0           Web           0  3.000000   
...         ...        ...          ...           ...         ...       ...   
838295       10      Urban            0           Web           0  3.500000   
547316        5      Urban            1         Phone           0  1.800000   
131575        6      Urban            1         Phone           0  4.000000   
603659        1  Surburban            1  Multichannel           0  3.200000   
254229        1  Surburban            0           Web           0  3.400000   

        total_amount     avg_price  count  
id                                         
906145  31333.333333  14016.666667      3  
184478  29000.000000   7250.000000      1  
394235  20500.000000   5125.000000      2  
130152  20750.000000  14875.000000      4  
940352  31000.000000  10333.333333      1  
...              ...           ...    ...  
838295  26000.000000   8012.500000      4  
547316  17800.000000  11300.000000      5  
131575  30500.000000   7833.333333      2  
603659  21600.000000   7583.333333      5  
254229  24400.000000   9280.000000      5  

[64000 rows x 9 columns]

In [20]:
data = pd.get_dummies(data, columns=['zip_code', 'channel'], drop_first=True)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(data.drop('conversion',axis=1),data['conversion'] ,test_size=.3, random_state=100)

In [23]:
X_train

recency  is_referral  num_item  total_amount     avg_price  count  \
id                                                                          
267034       11            1  2.333333  25000.000000  16416.666667      3   
154593        3            0  4.000000  11000.000000   2750.000000      1   
383594        7            1  3.000000  14000.000000   4875.000000      2   
975454        2            1  2.200000  21200.000000  13520.000000      5   
479835       10            1  4.000000  27000.000000   6750.000000      1   
...         ...          ...       ...           ...           ...    ...   
450144        8            1  3.000000  14666.666667   5611.111111      3   
694712       11            0  3.000000  11000.000000   3666.666667      1   
117566        3            0  2.000000  22750.000000  11375.000000      4   
219817        9            0  4.750000  19500.000000   4100.000000      4   
777536       10            1  3.000000  17500.000000   5625.000000      2   

        zip_code_Surburban  zip_code_Urban  channel_Phone  channel_Web  
id                                                                      
267034                   1               0              1            0  
154593                   0               0              1            0  
383594                   1               0              0            0  
975454                   1               0              1            0  
479835                   1               0              0            1  
...                    ...             ...            ...          ...  
450144                   1               0              1            0  
694712                   1               0              0            1  
117566                   1               0              0            0  
219817                   1               0              1            0  
777536                   1               0              1            0  

[44800 rows x 10 columns]

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
model = RandomForestClassifier(max_depth = 10,random_state=100)

In [26]:
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=100)

In [27]:
pred = model.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [29]:
accuracy_score(y_test, pred)

0.87515625

In [30]:
confusion_matrix(y_test, pred)

array([[16403,    60],
       [ 2337,   400]], dtype=int64)

In [31]:
from sklearn.metrics import classification_report

In [32]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.88      1.00      0.93     16463
           1       0.87      0.15      0.25      2737

    accuracy                           0.88     19200
   macro avg       0.87      0.57      0.59     19200
weighted avg       0.87      0.88      0.83     19200



In [33]:
from sklearn.ensemble import RandomForestRegressor

In [34]:
rf = RandomForestRegressor(max_depth=10, random_state=100)

In [35]:
rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=10, random_state=100)

In [38]:
pred = rf.predict(X_test)

In [42]:
df_pred = pd.DataFrame(pred)

In [46]:
df_pred.columns = ["value"]

In [41]:
def conv(value):
    if value >= 0.5:
        return 1
    else:
        return 0

In [47]:
df_pred["conv"] = df_pred['value'].apply(conv)

In [48]:
df_pred

value  conv
0      0.000000     0
1      0.058584     0
2      0.000000     0
3      0.594169     1
4      0.083316     0
...         ...   ...
19195  0.142431     0
19196  0.000000     0
19197  0.116323     0
19198  0.000000     0
19199  0.054583     0

[19200 rows x 2 columns]

In [49]:
accuracy_score(df_pred["conv"],y_test)

0.8799479166666667

In [50]:
confusion_matrix(y_test, df_pred["conv"])

array([[16313,   150],
       [ 2155,   582]], dtype=int64)

In [51]:
rf.feature_importances_

array([0.04990395, 0.02138491, 0.37591972, 0.1396865 , 0.23017582,
       0.16508618, 0.00303231, 0.00371579, 0.00697822, 0.0041166 ])

In [52]:
X_train.columns

Index(['recency', 'is_referral', 'num_item', 'total_amount', 'avg_price',
       'count', 'zip_code_Surburban', 'zip_code_Urban', 'channel_Phone',
       'channel_Web'],
      dtype='object')